version: '3.8'

services:
  markdown-converter:
    build: .
    container_name: markdown-to-docx-converter
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/"]
      interval: 30s
      timeout: 10s
      retries: 3